SELECT RULE_ID, RULE_NAME, pu.sname as USER_NAME,
       TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,
       COUNT(1) as COUNT
FROM SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm
LEFT JOIN PRM_USERS pu ON spm.NREVID = pu.lid
WHERE spm.CHANNEL_NAME = 'IMPC'
AND spm.REQUESTED_DATE BETWEEN TO_DATE('2026-05-08','YYYY-MM-DD') AND TO_DATE('2026-06-04','YYYY-MM-DD')
GROUP BY RULE_ID, RULE_NAME, pu.sname, REQUESTED_DATE
ORDER BY REQUESTED_DATE DESC;





WITH cte AS (
  SELECT ROW_NUMBER() OVER (PARTITION BY RULE_ID, RULE_NAME, pu.sname, REQUESTED_DATE ORDER BY NULL) AS row_num
  FROM SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm
  LEFT JOIN PRM_USERS pu ON spm.NREVID = pu.lid
  WHERE spm.CHANNEL_NAME = 'IMPC' 
  AND spm.REQUESTED_DATE BETWEEN TO_DATE('2026-05-08', 'YYYY-MM-DD') AND TO_DATE('2026-06-04', 'YYYY-MM-DD')
  GROUP BY RULE_ID, RULE_NAME, pu.sname, REQUESTED_DATE
)
SELECT COUNT(row_num) FROM cte;




SELECT RULE_ID, SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name, 
       pu.sname as USER_NAME, TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE, COUNT(1) as COUNT
FROM SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm
LEFT JOIN PRM_USERS pu ON spm.NREVID = pu.lid
WHERE spm.CHANNEL_NAME = 'IMPC' 
AND spm.REQUESTED_DATE BETWEEN TO_DATE('2026-05-08', 'YYYY-MM-DD') AND TO_DATE('2026-06-04', 'YYYY-MM-DD')
GROUP BY RULE_ID, RULE_NAME, pu.sname, REQUESTED_DATE
ORDER BY REQUESTED_DATE DESC
OFFSET NVL(1-1, 1) * 50 ROWS FETCH NEXT 50 ROWS ONLY;








-- Find the IMPC rows that the SQL returned
SELECT MESSAGE_ID, RULE_ID, RULE_NAME 
FROM SMS_PUSH_MESSAGE_LOG_CREDIT_AR
WHERE CHANNEL_NAME = 'IMPC'
AND REQUESTED_DATE BETWEEN TO_DATE('2026-05-08','YYYY-MM-DD') AND TO_DATE('2026-06-04','YYYY-MM-DD');

-- Then update ALL matching rows
UPDATE SMS_PUSH_MESSAGE_LOG_CREDIT_AR
SET RULE_ID = 9999, RULE_NAME = 'TEST_RULE'
WHERE CHANNEL_NAME = 'IMPC'
AND REQUESTED_DATE BETWEEN TO_DATE('2026-05-08','YYYY-MM-DD') AND TO_DATE('2026-06-04','YYYY-MM-DD');
COMMIT;
