SELECT RULE_ID, RULE_NAME, pu.sname as USER_NAME,
       TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,
       COUNT(1) as COUNT
FROM SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm
LEFT JOIN PRM_USERS pu ON spm.NREVID = pu.lid
WHERE spm.CHANNEL_NAME = 'IMPC'
AND spm.REQUESTED_DATE BETWEEN TO_DATE('2026-05-08','YYYY-MM-DD') AND TO_DATE('2026-06-04','YYYY-MM-DD')
GROUP BY RULE_ID, RULE_NAME, pu.sname, REQUESTED_DATE
ORDER BY REQUESTED_DATE DESC;
