### Credit Channels (UPFI, IMPC, NEFC, RTGC) MANUAL SMS (64 QUERIES) ###

## CommonExportSqlQueryDao ##

## getSMSExportMaskedSummaryReport:

getExportMaskedUPFISummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportMaskedIMPCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportMaskedNEFCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportMaskedRTGCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

## getSMSExportSummaryReport

getExportUPFISummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportIMPCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportNEFCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC

getExportRTGCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC


## getSMSArExportSummaryReport

getArExportUPFISummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportIMPCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportNEFCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportRTGCSummaryReport=select RULE_ID,RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

## getSMSArExportMaskedSummaryReport

getArExportMaskedUPFISummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportMaskedIMPCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportMaskedNEFCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc

getArExportMaskedRTGCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc


## getSMSExportDetailReport

getExportUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

## getSMSExportMaskedDetailReport

getExportMaskedUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportMaskedIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportMaskedNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getExportMaskedRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

## getSMSArExportDetailReport

getArExportUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
ACTION_LEVEL_KEY as DIMENSION_ID , PHONENUMBER as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

## getSMSArExportMaskedDetailReport

getArExportMaskedUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportMaskedIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportMaskedNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc

getArExportMaskedRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc


## CommonSqlQueryDao ##

## getSMSMaskedDetailReport:

getMaskedUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'UPFI' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY


getMaskedIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'IMPC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY


getMaskedNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'NEFC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getMaskedRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'RTGC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

## getSMSArMaskedDetailReport:

getArMaskedUPFIDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'UPFI' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedIMPCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'IMPC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedNEFCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'NEFC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedRTGCDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id,SUBSTR(rule_name,1,2)||RPAD('*',LENGTH(rule_name)-4,'*')||SUBSTR(rule_name,-3) as rule_name,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE,\
RESPONSE_DESC as SMS_STATUS,  \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
SUBSTR(ACTION_LEVEL_KEY,1,2)||RPAD('*',LENGTH(ACTION_LEVEL_KEY)-4,'*')||SUBSTR(ACTION_LEVEL_KEY,-3) as DIMENSION_ID , SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),1,2)||RPAD('*',LENGTH(COALESCE(SUBSTR(PHONENUMBER,-10),NULL))-4,'*')||SUBSTR(COALESCE(SUBSTR(PHONENUMBER,-10),NULL),-2) as PHONE_NUMBER  \
from \
SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME = 'RTGC' \
AND REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

## getSMSDetailReportCount

getUPFIDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL \
Where CHANNEL_NAME = 'UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getIMPCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL \
Where CHANNEL_NAME = 'IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getNEFCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL \
Where CHANNEL_NAME = 'NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getRTGCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL \
Where CHANNEL_NAME = 'RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

## getSMSArDetailReportCount

getArUPFIDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_AR \
Where CHANNEL_NAME='UPFI' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getArIMPCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_AR \
Where CHANNEL_NAME='IMPC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getArNEFCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_AR \
Where CHANNEL_NAME='NEFC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

getArRTGCDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CREDIT_AR \
Where CHANNEL_NAME='RTGC' and REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD')

## getSMSMaskedSummaryReport

getMaskedUPFISummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getMaskedIMPCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getMaskedNEFCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getMaskedRTGCSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

## getSMSSummaryReportCount

getUPFISummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getIMPCSummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getNEFCSummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getRTGCSummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_CHANNEL spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

## getSMSMaskedArSummaryReport

getArMaskedUPFISummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedIMPCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedNEFCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

getArMaskedRTGCSummaryReport=select RULE_ID,SUBSTR(RULE_NAME,1,2)||RPAD('*',LENGTH(RULE_NAME)-4,'*')||SUBSTR(RULE_NAME,-3) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY

## getSMSArSummaryReportCount

getArUPFISummaryReportCount=with cte as ( \
select  ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null)  as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='UPFI' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getArIMPCSummaryReportCount=with cte as ( \
select  ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null)  as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='IMPC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getArNEFCSummaryReportCount=with cte as ( \
select  ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null)  as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='NEFC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

getArRTGCSummaryReportCount=with cte as ( \
select  ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null)  as row_num \
from SMS_PUSH_MESSAGE_LOG_CREDIT_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.CHANNEL_NAME='RTGC' and spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD')  and TO_DATE( ? ,'YYYY-MM-DD') \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte

###  END  ###



####SMS Report#####
getReportChannelName=SELECT DISTINCT CHANNEL_NAME FROM DYNAMIC_CSM_CONFIG WHERE UPPER(CSM_NAME) LIKE ? ORDER BY CHANNEL_NAME

getSMSReportChannelName=SELECT DISTINCT CHANNEL_NAME FROM DYNAMIC_CSM_CONFIG WHERE UPPER(CSM_NAME) LIKE '%SMS%' ORDER BY CHANNEL_NAME
