getArMaskedCardSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME, pu.sname as USER_NAME, \
TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CARD_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND spm.CHANNEL_NAME='CARD' \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
order by REQUESTED_DATE desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY



getArCardSummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CARD_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND spm.CHANNEL_NAME='CARD' \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte


getMaskedCardSummaryReport=select RULE_ID,PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME,pu.sname as USER_NAME,TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,COUNT(1) as COUNT \
from SMS_PUSH_MESSAGE_LOG_CARD spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') and spm.CHANNEL_NAME='CARD' \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
ORDER BY REQUESTED_DATE DESC \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY


 
getCardSummaryReportCount=with cte as ( \
select ROW_NUMBER() over(partition by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE order by null) as row_num \
from SMS_PUSH_MESSAGE_LOG_CARD spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where spm.REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') and spm.CHANNEL_NAME='CARD' \
group by RULE_ID,RULE_NAME,pu.sname,REQUESTED_DATE \
) \
select count(row_num) from cte


 
getArMaskedCardDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID,rule_id, PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME, pu.sname as USER_NAME, \
TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE,TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE, RESPONSE_DESC as SMS_STATUS, \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
PF_MASK(ACTION_LEVEL_KEY,'*',2,2) AS DIMENSION_ID, PF_MASK(PHONENUMBER,'*',2,2) AS PHONE_NUMBER \
from SMS_PUSH_MESSAGE_LOG_CARD_AR spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND spm.CHANNEL_NAME='CARD' \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY




getArCardDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CARD_AR \
WHERE REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND CHANNEL_NAME='CARD'

 
getMaskedCardDetailReport=select /*+ parallel(2) */ MESSAGE_ID as ID, rule_id, PF_MASK(RULE_NAME,'*',2,2) AS RULE_NAME, pu.sname as USER_NAME, \
TO_CHAR(REQUESTED_DATE,'YYYY-MM-DD') AS REQUESTED_DATE, TO_CHAR(DD_PARTITION_DATE,'YYYY-MM-DD') AS DD_PARTITION_DATE, RESPONSE_DESC as SMS_STATUS, \
case when DTSUBMITTED1 is null then TO_CHAR(DTSUBMITTED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTSUBMITTED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_SUBMISSION_DATE, \
case when DTCOMPLETED1 is null then TO_CHAR(DTCOMPLETED2,'YYYY-MM-DD HH24:MI:SS') else TO_CHAR(DTCOMPLETED1,'YYYY-MM-DD HH24:MI:SS') end as SMS_DELIVERED_DATE, \
PF_MASK(ACTION_LEVEL_KEY,'*',2,2) AS DIMENSION_ID, PF_MASK(PHONENUMBER,'*',2,2) AS PHONE_NUMBER \
from SMS_PUSH_MESSAGE_LOG_CARD spm \
left join PRM_USERS pu on spm.NREVID=pu.lid \
Where REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND CHANNEL_NAME='CARD' \
order by MESSAGE_ID desc \
OFFSET nvl(? -1,1)* ? ROWS FETCH NEXT ? ROWS ONLY


getCardDetailReportCount=select count(1) from SMS_PUSH_MESSAGE_LOG_CARD \
Where REQUESTED_DATE BETWEEN TO_DATE( ? ,'YYYY-MM-DD') and TO_DATE( ? ,'YYYY-MM-DD') AND CHANNEL_NAME='CARD'
